#!/usr/bin/env node
var s3copy = require('./s3-copy');
var config = require(process.env["HOME"] + '/config');

var now = new Date();
var date = now.toJSON();

if(process.argv.length != 4) {
 console.log("Usage: s3cp <src> <dest>");
 return(-1);
}

var src = process.argv[2];
var dest = process.argv[3];

s3copy.copy_to_s3(config, src, 'beagleboard', dest + '-' + date, oncomplete);

function oncomplete(err) {
 if(err) console.log("Error: " + err);
 console.log("Completed copy from " + src + " to beagleboard/" + dest + "-" + date);
}
